spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_order_db
    username: postgres
    password: Harsha@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql

#
#    properties:
#      hibernate:
#        format_sql: true
