name: Build with Maven

on:
  push:
    branches:
      - master  # Trigger on pushes to master branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven using CI profile
        run: ./mvnw clean install -Dspring.profiles.active=ci
