name: Spring Boot CI with Liquibase

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: customerdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up PostgreSQL driver
        run: sudo apt-get install -y libpq-dev

      - name: Build with Maven
        run: ./mvnw clean install -Dspring.profiles.active=ci

      - name: Run Liquibase migrations
        run: ./mvnw liquibase:update -Dspring.profiles.active=ci

      - name: Run Tests
        run: ./mvnw test -Dspring.profiles.active=ci

      - name: Health Check
        run: |
          nohup ./mvnw spring-boot:run -Dspring-boot.run.profiles=ci &
          sleep 30
          curl -f http://localhost:8080/actuator/health
